package com.jiaming.mapper;

import com.jiaming.entity.Book;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BookMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table book
	 *
	 * @mbggenerated Tue Jun 23 15:02:12 CST 2020
	 */
	int deleteByPrimaryKey(String bid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table book
	 *
	 * @mbggenerated Tue Jun 23 15:02:12 CST 2020
	 */
	int insert(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table book
	 *
	 * @mbggenerated Tue Jun 23 15:02:12 CST 2020
	 */
	Book selectByPrimaryKey(String bid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table book
	 *
	 * @mbggenerated Tue Jun 23 15:02:12 CST 2020
	 */
	List<Book> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table book
	 *
	 * @mbggenerated Tue Jun 23 15:02:12 CST 2020
	 */
	int updateByPrimaryKey(Book record);

	// 左边条目查询书
	List<Book> selectBooksByCid(String cid);

	// 查询
	List<Book> selectBooksLikeBnameOrAuthorOrPress(@Param("word") String word);

	// 查询
	List<Book> selectBooksLikeBnameOrAuthor(@Param("keyword1") String keyword1, @Param("keyword2") String keyword2);

	// 高级搜索
	List<Book> selectBooksByGj(Book book);
	
	List<Book> selectBooksByExample(Book book);
}