package com.jiaming.mapper;

import com.jiaming.entity.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    boolean insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    User selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    boolean updateByPrimaryKey(User record);

    //验证用户名
	User selectUserByLoginname(String loginname);
	
	//验证邮箱
	User selectUserByEmail(String email);
	
	//邮箱中激活
	User seleUserByActivationCode(String activationCode);
	
	//登录
	User selectUserByLoginnameAndLoginpass(User user);
}