package com.jiaming.entity;

import java.math.BigDecimal;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bname
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.currPrice
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private BigDecimal currprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.discount
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.edition
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private Integer edition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pageNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private Integer pagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.wordNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private Integer wordnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.printtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String printtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.booksize
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private Integer booksize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.paper
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String paper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.image_w
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String imageW;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.image_b
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private String imageB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.orderBy
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    private Integer orderby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bid
     *
     * @return the value of book.bid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bid
     *
     * @param bid the value for book.bid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bname
     *
     * @return the value of book.bname
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bname
     *
     * @param bname the value for book.bname
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.currPrice
     *
     * @return the value of book.currPrice
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public BigDecimal getCurrprice() {
        return currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.currPrice
     *
     * @param currprice the value for book.currPrice
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setCurrprice(BigDecimal currprice) {
        this.currprice = currprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.discount
     *
     * @return the value of book.discount
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.discount
     *
     * @param discount the value for book.discount
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishtime
     *
     * @return the value of book.publishtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishtime
     *
     * @param publishtime the value for book.publishtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime == null ? null : publishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.edition
     *
     * @return the value of book.edition
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.edition
     *
     * @param edition the value for book.edition
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pageNum
     *
     * @return the value of book.pageNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public Integer getPagenum() {
        return pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pageNum
     *
     * @param pagenum the value for book.pageNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPagenum(Integer pagenum) {
        this.pagenum = pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.wordNum
     *
     * @return the value of book.wordNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public Integer getWordnum() {
        return wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.wordNum
     *
     * @param wordnum the value for book.wordNum
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setWordnum(Integer wordnum) {
        this.wordnum = wordnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.printtime
     *
     * @return the value of book.printtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getPrinttime() {
        return printtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.printtime
     *
     * @param printtime the value for book.printtime
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPrinttime(String printtime) {
        this.printtime = printtime == null ? null : printtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.booksize
     *
     * @return the value of book.booksize
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public Integer getBooksize() {
        return booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.booksize
     *
     * @param booksize the value for book.booksize
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setBooksize(Integer booksize) {
        this.booksize = booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.paper
     *
     * @return the value of book.paper
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getPaper() {
        return paper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.paper
     *
     * @param paper the value for book.paper
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setPaper(String paper) {
        this.paper = paper == null ? null : paper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cid
     *
     * @return the value of book.cid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cid
     *
     * @param cid the value for book.cid
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.image_w
     *
     * @return the value of book.image_w
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getImageW() {
        return imageW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.image_w
     *
     * @param imageW the value for book.image_w
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setImageW(String imageW) {
        this.imageW = imageW == null ? null : imageW.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.image_b
     *
     * @return the value of book.image_b
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public String getImageB() {
        return imageB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.image_b
     *
     * @param imageB the value for book.image_b
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setImageB(String imageB) {
        this.imageB = imageB == null ? null : imageB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.orderBy
     *
     * @return the value of book.orderBy
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.orderBy
     *
     * @param orderby the value for book.orderBy
     *
     * @mbggenerated Tue Jun 23 15:02:12 CST 2020
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}